packages:
  libfabric:
    buildable: false
    externals:
    - spec: libfabric@1.15.0.0
      prefix: /opt/cray/libfabric/1.15.0.0/
  slurm:
    buildable: false
    externals:
    - spec: slurm@20-11-9
      prefix: /usr
  rdma-core:
    buildable: false
    externals:
    - spec: rdma-core@39.1
      prefix: /usr
  xpmem:
    buildable: false
    externals:
    - spec: xpmem@0.29.2
      prefix: /opt/cray/xpmem/2.4.4-2.3_9.1__gff0e1d9.shasta
